name = "live-app"
main = "./functions/_worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

[assets]
directory = "./public"

[vars]
BROADCAST_KEY = "SECRET"
ALLOWED_ORIGINS = ""

[[durable_objects.bindings]]
name = "RELAY"
class_name = "Relay"

[[migrations]]
tag = "v1"
new_classes = ["Relay"]

[observability]
enabled = true
