name = "live-app"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./public"
workers_dev = true

[assets]
binding = "ASSETS"
directory = "./public"

[vars]
BROADCAST_KEY = "SECRET"
ALLOWED_ORIGINS = ""

[[durable_objects.bindings]]
name = "RELAY"
class_name = "Relay"

[[migrations]]
tag = "v1"
new_classes = ["Relay"]

[observability]
enabled = true
