name = "live-app"
compatibility_date = "2024-05-02"
workers_dev = true

[vars]
BROADCAST_KEY = "SECRET"
ALLOWED_ORIGINS = ""

[[durable_objects.bindings]]
name = "RELAY"
class_name = "Relay"

[[migrations]]
tag = "v1"
new_classes = ["Relay"]

[observability]
enabled = true
